[package]
name = "rugol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.6"
egui-tetra = "0.2"
egui = "0.14"
rand = "0.8"
